; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Apr 14 2019 16:19:36 GMT+0300 (FLE Summer Time)
; ================================================================================

beermap:
	dc.w beermap_0-beermap, beermap_1-beermap
	dc.w beermap_2-beermap
beermap_0: dc.b $1
	dc.b $F4, $6, $20, $0, $F8
beermap_1: dc.b $1
	dc.b $F4, $6, $20, $0, $F8
beermap_2: dc.b $1
	dc.b $F4, $6, $20, $0, $F8
	even