; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Mar 23 2019 16:13:01 GMT+0200 (FLE Standard Time)
; ================================================================================

git_gud:
	dc.w git_gud_0-git_gud, git_gud_1-git_gud
	dc.w git_gud_2-git_gud, git_gud_3-git_gud
git_gud_0: dc.b $3
	dc.b $F3, $5, $0, $1C, $FF
	dc.b $F3, $1, $0, $20, $F8
	dc.b $F3, $5, $0, $14, $E7
git_gud_1: dc.b $3
	dc.b $4, $5, $0, $14, $FA
	dc.b $4, $5, $0, $18, $8
	dc.b $4, $5, $0, $C, $17
git_gud_2: dc.b $3
	dc.b $F3, $5, $0, $1C, $FF
	dc.b $F3, $1, $0, $20, $F8
	dc.b $F3, $5, $0, $14, $E7
git_gud_3: dc.b $3
	dc.b $4, $5, $0, $14, $FA
	dc.b $4, $5, $0, $18, $8
	dc.b $4, $5, $0, $C, $17
	even