; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Apr 28 2019 15:40:34 GMT+0300 (FLE Summer Time)
; ================================================================================

Map_GBall_internal:
	dc.w @shiny-Map_GBall_internal
	dc.w @check1-Map_GBall_internal
	dc.w @check2-Map_GBall_internal
	dc.w @check3-Map_GBall_internal
@shiny: dc.b $4
	dc.b $F0, $F, $0, $26, $EC
	dc.b $E8, $C, $0, $36, $F4
	dc.b $10, $8, $0, $3A, $F4
	dc.b $F0, $3, $0, $3D, $C
@check1: dc.b $4
	dc.b $F0, $F, $0, $26, $EC
	dc.b $E8, $C, $0, $36, $F4
	dc.b $10, $8, $0, $3A, $F4
	dc.b $F0, $3, $0, $3D, $C
@check2: dc.b $4
	dc.b $F0, $F, $0, $26, $EC
	dc.b $E8, $C, $0, $36, $F4
	dc.b $10, $8, $0, $3A, $F4
	dc.b $F0, $3, $0, $3D, $C
@check3: dc.b $4
	dc.b $F0, $F, $0, $26, $EC
	dc.b $E8, $C, $0, $36, $F4
	dc.b $10, $8, $0, $3A, $F4
	dc.b $F0, $3, $0, $3D, $C
	even
