; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Apr 28 2019 17:22:38 GMT+0300 (FLE Summer Time)
; ================================================================================

DATAL9O53LM6XQT:
	dc.w DATAL9O53LM6XQT_0-DATAL9O53LM6XQT, DATAL9O53LM6XQT_1-DATAL9O53LM6XQT
	dc.w DATAL9O53LM6XQT_2-DATAL9O53LM6XQT, DATAL9O53LM6XQT_3-DATAL9O53LM6XQT
DATAL9O53LM6XQT_0: dc.b $4
	dc.b $F0, $F, $0, $0, $EC
	dc.b $E8, $C, $0, $10, $F4
	dc.b $10, $8, $0, $14, $F4
	dc.b $F0, $3, $0, $17, $C
DATAL9O53LM6XQT_1: dc.b $4
	dc.b $F0, $F, $0, $0, $EC
	dc.b $E8, $C, $0, $10, $F4
	dc.b $10, $8, $0, $14, $F4
	dc.b $F0, $3, $0, $17, $C
DATAL9O53LM6XQT_2: dc.b $4
	dc.b $F0, $F, $0, $0, $EC
	dc.b $E8, $C, $0, $10, $F4
	dc.b $10, $8, $0, $14, $F4
	dc.b $F0, $3, $0, $17, $C
DATAL9O53LM6XQT_3: dc.b $4
	dc.b $F0, $F, $0, $0, $EC
	dc.b $E8, $C, $0, $10, $F4
	dc.b $10, $8, $0, $14, $F4
	dc.b $F0, $3, $0, $17, $C
	even