; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Apr 28 2019 13:36:17 GMT+0300 (FLE Summer Time)
; ================================================================================

DATAQ1OE4X3Y2NK:
	dc.w DATAQ1OE4X3Y2NK_0-DATAQ1OE4X3Y2NK, DATAQ1OE4X3Y2NK_1-DATAQ1OE4X3Y2NK
	dc.w DATAQ1OE4X3Y2NK_2-DATAQ1OE4X3Y2NK, DATAQ1OE4X3Y2NK_3-DATAQ1OE4X3Y2NK
	dc.w DATAQ1OE4X3Y2NK_4-DATAQ1OE4X3Y2NK
DATAQ1OE4X3Y2NK_0: dc.b $4
	dc.b $F0, $F, $0, $26, $EC
	dc.b $E8, $C, $0, $36, $F4
	dc.b $10, $8, $0, $3A, $F4
	dc.b $F0, $3, $0, $3D, $C
DATAQ1OE4X3Y2NK_1: dc.b $4
	dc.b $F0, $F, $0, $26, $EC
	dc.b $E8, $C, $0, $36, $F4
	dc.b $10, $8, $0, $3A, $F4
	dc.b $F0, $3, $0, $3D, $C
DATAQ1OE4X3Y2NK_2: dc.b $4
	dc.b $F0, $F, $0, $26, $EC
	dc.b $E8, $C, $0, $36, $F4
	dc.b $10, $8, $0, $3A, $F4
	dc.b $F0, $3, $0, $3D, $C
DATAQ1OE4X3Y2NK_3: dc.b $4
	dc.b $F0, $F, $0, $26, $EC
	dc.b $E8, $C, $0, $36, $F4
	dc.b $10, $8, $0, $3A, $F4
	dc.b $F0, $3, $0, $3D, $C
DATAQ1OE4X3Y2NK_4: dc.b $4
	dc.b $F0, $F, $0, $26, $EC
	dc.b $E8, $C, $0, $36, $F4
	dc.b $10, $8, $0, $3A, $F4
	dc.b $F0, $3, $0, $3D, $C
	even