; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun May 19 2019 12:20:52 GMT+0300 (FLE Summer Time)
; ================================================================================

DATAO0NTF1HLAHP:
	dc.w DATAO0NTF1HLAHP_0-DATAO0NTF1HLAHP, DATAO0NTF1HLAHP_1-DATAO0NTF1HLAHP
	dc.w DATAO0NTF1HLAHP_2-DATAO0NTF1HLAHP, DATAO0NTF1HLAHP_3-DATAO0NTF1HLAHP
	dc.w DATAO0NTF1HLAHP_4-DATAO0NTF1HLAHP, DATAO0NTF1HLAHP_5-DATAO0NTF1HLAHP
	dc.w DATAO0NTF1HLAHP_6-DATAO0NTF1HLAHP, DATAO0NTF1HLAHP_7-DATAO0NTF1HLAHP
	dc.w DATAO0NTF1HLAHP_8-DATAO0NTF1HLAHP, DATAO0NTF1HLAHP_9-DATAO0NTF1HLAHP
	dc.w DATAO0NTF1HLAHP_A-DATAO0NTF1HLAHP, DATAO0NTF1HLAHP_B-DATAO0NTF1HLAHP
DATAO0NTF1HLAHP_0: dc.b $1
	dc.b $EF, $F, $0, $0, $F0
DATAO0NTF1HLAHP_1: dc.b $2
	dc.b $F5, $5, $0, $10, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAO0NTF1HLAHP_2: dc.b $2
	dc.b $F5, $5, $0, $14, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAO0NTF1HLAHP_3: dc.b $2
	dc.b $F5, $5, $0, $18, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAO0NTF1HLAHP_4: dc.b $2
	dc.b $F5, $5, $0, $1C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAO0NTF1HLAHP_5: dc.b $2
	dc.b $F5, $5, $0, $24, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAO0NTF1HLAHP_6: dc.b $2
	dc.b $F5, $5, $0, $28, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAO0NTF1HLAHP_7: dc.b $2
	dc.b $F5, $5, $0, $2C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAO0NTF1HLAHP_8: dc.b $2
	dc.b $F5, $5, $0, $30, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAO0NTF1HLAHP_9: dc.b $2
	dc.b $F5, $5, $0, $34, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAO0NTF1HLAHP_A: dc.b $2
	dc.b $F5, $5, $0, $20, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAO0NTF1HLAHP_B: dc.b $1
	dc.b $FF, $D, $0, $38, $F0
	even